move "check_sum_small.gif" OLD\
move "chameleon_smallgif.gif" OLD\
move "pamela1.jpg" OLD\
move "tutan_02.gif" OLD\
move "galaga.gif" OLD\
move "counter.gif" OLD\
move "anim_chain_links.gif" OLD\
move "construc.gif" OLD\
move "slider.gif" OLD\
move "invaders.gif" OLD\
move "anim_altered_beast_small.gif" OLD\
move "anim_invaders.gif" OLD\
move "anim_galaga_2.gif" OLD\
move "VideoSubTitleTools__v1,0f__CQUni.png" OLD\
move "Oblotteration__04_help_about_dialog.png" OLD\
move "Oblotteration__01_start_of_game.png" OLD\
move "Oblotteration__03_game_over.png" OLD\
move "Apple_Panic__Title_Screen_and_End_of_Game_Screen__filled_in__with_description.png" OLD\
move "Apple_Panic__title_screen__filled_in.png" OLD\
move "apple2_Apple_Panic__Level_48__END_of_Game_screen__filled_in.png" OLD\
move "Millionwaire_Remake_v1,1f__title_screen_Windows_10.png" OLD\
move "Millionwaire_Remake_v1,0f__Windows_10.png" OLD\
move "sticky-note-pencil-icon.png" OLD\
move "Bitwise_Encryptor_Decryptor__v1,0f__analysis_screen__Windows_10.png" OLD\
move "QI_TV_Show_Unofficial_Companion__v1,0f__release__stats_after_1_month.png" OLD\
move "Mooses_Software_Valley__banner__with_code_background and Established July, 1996.gif" OLD\
move "QI_TV_Show_Unofficial_Companion__v1,0f__main_screen.jpg" OLD\
move "File_Usage_Monitor__v1,6f.png" OLD\
move "Sudoku_Solver_Helper_Trainer__v1,1f__2_screen.png" OLD\
move "CPU_Usage_Drop_Alarm__v1,0f.png" OLD\
move "Ram_Swap__v5,1f.png" OLD\
move "Ram_Swap__v5,0f.png" OLD\
move "ram_swap__v4,9f.png" OLD\
move "Mooses_Software_Valley__banner__with_code_background.gif" OLD\
move "About_Screen_V5.png" OLD\
move "sanitize_disk_space_2,2f_screen_shots.gif" OLD\
move "Mooses_Software_Valley__banner - no background.gif" OLD\
move "Windows_10__Sag_Calculator_v3.6__small.jpg" OLD\
move "sanitize_disk_space_2,1f.gif" OLD\
move "Supaplex__Moose_Level_88.jpg" OLD\
move "Sag_Calculator_Cable_Tab__series_dyn.gif" OLD\
move "moose_avitar.png" OLD\
move "Solar_System_Simulator__v2,3f.gif" OLD\
move "LCD_Radius_320.jpg" OLD\
move "LCD_Sharp_Triple_Directional_Viewing_LCD.jpg" OLD\
move "MIG_Jet_Adventures_small2.jpg" OLD\
move "MIG_Jet_Adventures_small.jpg" OLD\
move "goodies_still_alive_on_stage.jpg" OLD\
move "pacman_hat.jpg" OLD\
move "Computer_Space_Simulator__Game_Play.gif" OLD\
move "cqu_ic_logo.gif" OLD\
move "dog_world_ugliest5.jpg" OLD\
move "dog_world_ugliest4.jpg" OLD\
move "Mosaic_Maker_Extractor.jpg" OLD\
move "Moose_Avatar.jpg" OLD\
move "paypal_donate3.gif" OLD\
move "seismograph__mt_st_helens.jpg" OLD\
move "paypal_logo_creditCards_169x21.gif" OLD\
move "paypal_logo2.gif" OLD\
move "paypal_logo2_donate.gif" OLD\
move "paypal_donate.gif" OLD\
move "TRON_Jay_M_portrait.jpg" OLD\
move "ram_swap__v4,8f.gif" OLD\
move "Yahtzee_small_2.gif" OLD\
move "doom_staked_out.gif" OLD\
move "doom_chainsaw_revenge.gif" OLD\
move "doom_logo.gif" OLD\
move "TV_Card__Pinnacle_PC_TV.jpg" OLD\
move "Linux_Logo.gif" OLD\
move "Mooses_Software_On_MAME_32_CL_1_Aug_2003.jpg" OLD\
move "Mooses_Software_On_MAME_World_1_Aug_2003.jpg" OLD\
move "mouse_od__v1,6f.gif" OLD\
move "moon_landing_movie_clip_lunar_rover.jpg" OLD\
move "moon_landing_movie_clip_moon_walk.jpg" OLD\
move "moon_landing_movie_clip_flag.jpg" OLD\
move "moon_landing_movie_clip_lander.jpg" OLD\
move "movie.bmp" OLD\
move "Big_Bertha__Mother_of_all_Bombs.jpg" OLD\
move "michelin_man.gif" OLD\
move "moon_landing_lunar_buggy.jpg" OLD\
move "moon_landing_rocket_plume.jpg" OLD\
move "moon_landing_neil_armstrongs_first_step.jpg" OLD\
move "moon_landing_movie_clip.jpg" OLD\
move "moon_landing_flag.jpg" OLD\
move "moon_rock.jpg" OLD\
move "moon_landing.jpg" OLD\
move "moon_landing_neil_armstrongs_footprint.jpg" OLD\
move "moon_landing_buzz_aldrin_july_1969.jpg" OLD\
move "sag32.gif" OLD\
move "credit card - bankcard.jpg" OLD\
move "gta.jpg" OLD\
move "mame_t_shirt2.jpg" OLD\
move "file_mon__v1,5f.gif" OLD\
move "disk_mon__v3,6f.gif" OLD\
move "clpbdclr_1,1f.gif" OLD\
move "About_Screen_V4.gif" OLD\
move "credit_card_horizontal.gif" OLD\
move "astronomy_hyakutake_comet.jpg" OLD\
move "book_accidental_empires_richard_x_cringley_back.jpg" OLD\
move "apple2_broderbund.jpg" OLD\
move "book_accidental_empires_richard_x_cringley.jpg" OLD\
move "email_me.gif" OLD\
move "previous_web_page_changes.gif" OLD\
move "MAME_Keyboard_Map_conservative.gif" OLD\
move "windows_32_family.jpg" OLD\
move "omf_battlegrounds_title_screen.jpg" OLD\
move "House - Bathroom - 4a.JPG" OLD\
move "xbox_mame2.gif" OLD\
move "xbox_mame.gif" OLD\
move "background_blue_scan_lines.gif" OLD\
move "mamelogo-c.gif" OLD\
move "mac_osx_my_feedback_to_apple_via_their_feedback_form.jpg" OLD\
move "microsoft_dotnet_visual_studio.gif" OLD\
move "book_exploring_applesoft.jpg" OLD\
move "Windows_OS_logo.gif" OLD\
move "turbo_pascal_v3.gif" OLD\
move "windows_3.0_ready_to_run.jpg" OLD\
move "ibm_pc_386sx.jpg" OLD\
move "book_cobol.jpg" OLD\
move "macintosh_128_512k.gif" OLD\
move "apple_2_logo_on_apple2_screen_red.gif" OLD\
move "book_accidental_empires_richard_x_cringley_small.jpg" OLD\
move "book_accidental_empires_richard_x_cringley_back_small.jpg" OLD\
move "ms_flight_simulator_v3.0.jpg" OLD\
move "book_basic_with_business_applications.jpg" OLD\
move "book_more_basic_computer_games.jpg" OLD\
move "book_basic_computer_games.jpg" OLD\
move "book_apple_2_basic_programming_reference.jpg" OLD\
move "book_numerical_analysis.jpg" OLD\
move "book_peter_nortons_assembly_language_for_ibm_pc.jpg" OLD\
move "book_computer_graphics_primer.jpg" OLD\
move "basic_battle_games.jpg" OLD\
move "book_trs80_basic.jpg" OLD\
move "book_forth.jpg" OLD\
move "book_fortran_77.jpg" OLD\
move "basic_space_games.jpg" OLD\
move "int_dload.gif" OLD\
move "int_dload_small.gif" OLD\
move "apple_2_tape_small.gif" OLD\
move "apple_2_tape.jpg" OLD\
move "apple2_castle_wolfenstein_small.gif" OLD\
move "apple2_castle_wolfenstein_title_small.gif" OLD\
move "apple2_castle_wolfenstein.gif" OLD\
move "apple2_castle_wolfenstein_title.gif" OLD\
move "apple2_broderbund_small.gif" OLD\
move "apple2_floppy_disk_1980_small.gif" OLD\
move "beaglebros_poke_all_night_long_small.gif" OLD\
move "apple2_floppy_disk_1980_notch.gif" OLD\
move "apple_2_inventors.gif" OLD\
move "apple2_dinoeggs_small.gif" OLD\
move "apple2_dinoeggs.gif" OLD\
move "apple2_choplifter_small.gif" OLD\
move "apple2_aztek_small.gif" OLD\
move "apple2_apple_panic_small.gif" OLD\
move "apple2_music_comp_small.gif" OLD\
move "apple2_swashbuckler_small.gif" OLD\
move "apple2_starblazer_small.gif" OLD\
move "apple2_swashbuckler.gif" OLD\
move "apple2_starblazer.gif" OLD\
move "apple2_music_comp.gif" OLD\
move "apple2_aztek.gif" OLD\
move "apple2_bilestoad.gif" OLD\
move "apple2_choplifter.gif" OLD\
move "apple2_bilestoad_small.gif" OLD\
move "pong_arcade.gif" OLD\
move "apple_2_tape_storage.gif" OLD\
move "apple_2_disk_ii.gif" OLD\
move "apple_2_computer.gif" OLD\
move "apple_2_logo_on_apple2_screen.gif" OLD\
move "beaglebros_poke_all_night_long.gif" OLD\
move "beaglebros_micro_software_small.gif" OLD\
move "beaglebros_disk_warnings.jpg" OLD\
move "beaglebros_micro_software.jpg" OLD\
move "apple2_floppy_disk_1980.jpg" OLD\
move "improv_logo.bmp" OLD\
move "improv_box_back_medium.jpg" OLD\
move "improv_box_front_medium.jpg" OLD\
move "improv_box_front_small.jpg" OLD\
move "improv_box_back_small.jpg" OLD\
move "improv_8_dialog_editor.gif" OLD\
move "improv_6_formulas.gif" OLD\
move "improv_7_lotus_script.gif" OLD\
move "improv_5_move_around_dimensions_1.gif" OLD\
move "improv_4_rename_dims_add_years.gif" OLD\
move "improv_3_drag_days.gif" OLD\
move "improv_2_drag_months.gif" OLD\
move "improv_1_start.gif" OLD\
move "units_lotus_improv.gif" OLD\
move "fileload.gif" OLD\
move "sag_small.gif" OLD\
move "invader2.gif" OLD\
move "dkong.gif" OLD\
move "joust.gif" OLD\
move "mrdo.gif" OLD\
move "gauntlet.gif" OLD\
move "defender.gif" OLD\
move "robotron.gif" OLD\
move "star_castle_small.gif" OLD\
move "star_castle.gif" OLD\
move "battlezone_military.png" OLD\
move "line-blue-marble.gif" OLD\
move "apple_2_Brochure_1979.jpg" OLD\
move "apple_IIc.gif" OLD\
move "About_Screen_V3.gif" OLD\
move "About_Screen_V2.gif" OLD\
move "About_Screen_V1.gif" OLD\
move "skycar_on_lawn.gif" OLD\
move "skycar_m400.jpg" OLD\
move "winzip_logo.gif" OLD\
move "chameleon_small.gif" OLD\
move "delphi_logo.jpg" OLD\
move "installer.gif" OLD\
move "Marbel_Man.jpg" OLD\
move "JoseQs_EmuViews.gif" OLD\
move "Daves_VGN.gif" OLD\
move "mo_button5.gif" OLD\
move "mo_button7.gif" OLD\
move "mo_button6.gif" OLD\
move "credit_card.gif" OLD\
move "shareware_palace.gif" OLD\
move "shareware_simply_the_best.gif" OLD\
move "robocop.png" OLD\
move "justadded.gif" OLD\
move "sharemon_small.gif" OLD\
move "file_mon_small_2.gif" OLD\
move "File_Usage_Monitor__small_2.gif" OLD\
move "file_mon_small.gif" OLD\
pause
